### ISSUE TITLE
feature: Add progress indicator for sending messages in a loop.

### ISSUE THREAD

**Issue by piotr-lesniak** [grzegorz-wolszczak/kafka-message-tool#7]
Add progress indicator for sending messages in a loop.
Progress can be counted in percentage 
or as number of sent messages / total number of messages.

It would help testers to figure out how long do they have to wait for test to complete.

**Comment by Rviku** [comment]
I'll take that issue.

**Comment by grzegorz-wolszczak** [comment]
implemented in version v.1.0.3.0
